name: ESP IDF artifact builder
description: "Saves compiled esp-idf project as an artifact"
author: tobozo
branding:
  icon: 'aperture'
  color: 'black'

on:
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**.yml'
    - 'CMakeLists.txt'
  pull_request:
  workflow_dispatch:

inputs:

  target_repo:
    description: "Target repo [author/repo-name]" # source project
    required: true

  target_repo_ref:
    description: "Target repo ref/branch"
    default: ""

  idf_version:
    description: "IDF Docker image version"
    default: "v5.1" # idf version, must match a tag listed at https://hub.docker.com/r/espressif/idf/tags

  idf_target_chip:
    description: "Target chip"
    default: "esp32" # esp32 / esp32s2 / esp32s3 / etc

  idf_project_folder:
    description: "Project folder" # relative to target_repo
    default: "."

  merged_bin:
    description: "Merged binary file name"
    default: "merged.bin" # will be saved as an artifact

  artifact_name:
    description: "Artifact name"
    default: "merged-bin"

runs:
  using: "composite"

  steps:

  - name: Checkout repo
    uses: actions/checkout@v4
    with:
      submodules: 'recursive'
      repository: ${{inputs.target_repo}}
      ref: ${{inputs.target_repo_ref}}
      #path: application

  - name: Check inputs
    shell: bash
    run: |
      rx_art='^([a-zA-Z0-9_.\-]+)$'
      rx_ver='^v([0-9]+\.){0,2}(\*|[0-9]+)$'
      rx_esp='^esp32([a-z0-9]{0,2})$'
      [[ ${{ inputs.artifact_name }} =~ $rx_art ]] || { echo "Bad artifact_name" && exit 1; }
      [[ ${{ inputs.idf_version }} =~ $rx_ver ]] || { echo "Bad idf_version" && exit 1; }
      [[ ${{ inputs.idf_target_chip }} =~ $rx_esp ]] || { echo "Bad idf_target_chip" && exit 1; }
      [[ -d "${{ inputs.idf_project_folder }}" ]] || { echo "Bad idf_project_folder" && exit 1; }
      [[ "${{ inputs.merged_bin }}" = "`basename ${{ inputs.merged_bin }}`" ]] || { echo "Bad merged_bin" && exit 1; }

  - name: esp-idf build
    uses: espressif/esp-idf-ci-action@v1
    with:
      esp_idf_version: ${{inputs.idf_version}}
      target: ${{inputs.idf_target_chip}}
      path: ${{ inputs.idf_project_folder }}
      command: ls ../../ -la && { idf.py build || { cat /app/tobozo/idf-builder/examples/touch-tma340/build/CMakeFiles/CMakeOutput.log && exit 1; } } && cd build && esptool.py --chip ${{inputs.idf_target_chip}} merge_bin -o ../${{inputs.merged_bin}} @flash_args

  - name: "Artifact upload"
    uses: actions/upload-artifact@v4
    with:
      name: ${{inputs.artifact_name}}
      path: ${{ inputs.idf_project_folder }}/${{inputs.MERGED_BIN}}


