name: IDFBuild

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test Action
      uses: tobozo/idf-builder@test
      with:
        target_repo: tobozo/epdiy
        target_repo_ref: s3_color_implementation
        idf_project_folder: examples/touch-tma340
        idf_version: v5.1
        idf_target_chip: esp32s3
        # merged_bin: lv_port_esp32s3_merged.bin
        # artifact_name: lv_port_esp32s3_merged_bin



